# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
      # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: nexVega
      POSTGRES_USER: nexVega
      POSTGRES_DB: nexVega

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
